# 该脚本是为了避免脚本自动关闭（Github 公共仓库无代码活动60天自动关闭 Action）

name: Log Current Date For Active Action

on:
  workflow_dispatch:
  schedule:
    - cron: "30 0 * * *" # 每天 0：30 时运行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Use Node@14.x # 步骤2
        uses: actions/setup-node@v1 # 作用：安装nodejs
        with:
          node-version: 14.x

      - name: current date
        run: npm run logDay

      - name: Commit and push if changed
        run: |-
          git diff
          git config --global user.email "sss213018@163.com"
          git config --global user.name "JS-banana"
          git pull
          git add -A
          git commit -m "Updated current date" || exit 0
          git push