name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 598ad953-0c9e-40d7-ae6d-7e14f7f5704f
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
